backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: '{{slug}}'
    fields: # The fields for each document, usually in front matter
      - label: "SKU"
        name: "id"
        widget: "string"

      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Price"
        name: "price"
        widget: "number"
        valueType: "float"
        min: 0

      - label: "Image"
        name: "image"
        widget: "image"
        default: "/uploads/lovelee-rolls-logo-square.jpg"

      - label: "Description"
        name: "description"
        widget: "text"

  - name: "settings"
    label: "Settings"
    file: "content/settings.yml"
    editor:
      preview: false
    fields:
        - label: "Available Days"
          name: "available days"
          widget: list
          fields:
            - label: "Date"
              name: "date"
              widget: "date"
