backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'products'
    label: 'Products'
    folder: 'content/products'
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "SKU", name: "sku", widget: "string"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number", valueType: "float", min: 0}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
